name: protopipe
channels:
  - defaults
  - conda-forge
  - cta-observatory
dependencies:
  - ctapipe=0.9.1
  - gammapy=0.8
  - astropy>=4.0.1
  - ipython
  - nbsphinx
  - numpydoc
  - pandas
  - pytest
  - sphinx-automodapi
  - sphinx_rtd_theme
  - vitables
