name: protopipe
channels:
  - defaults
  - conda-forge
  - cta-observatory
dependencies:
  - ctapipe=0.9.1
  - gammapy=0.8
  - astropy=3.2.3
  - ipython
  - jupyterlab
  - nbsphinx
  - notebook
  - numpydoc
  - pandas
  - pytest
  - sphinx-automodapi
  - sphinx_rtd_theme
  - uproot
  - vitables
