name: protopipe
channels:
  - defaults
  - conda-forge
  - cta-observatory
dependencies:
  - ctapipe
  - gammapy
  - ipython
  - nbsphinx
  - numpydoc
  - pandas
  - pytest
  - sphinx-automodapi
  - sphinx_rtd_theme
  - vitables
  - pip:
    - Cython
    - pyirf