name: protopipe
channels:
  - conda-forge
  - cta-observatory
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=1.2.0
  - astropy=3.2.2
  - atomicwrites=1.3.0
  - attrs=19.2.0
  - babel=2.7.0
  - blas=1.0
  - blosc=1.16.3
  - bokeh=1.3.4
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.0
  - chardet=3.0.4
  - click=7.0
  - corsikaio=0.2.0
  - cryptography=2.7
  - ctapipe=0.7.0
  - ctapipe-extra=0.2.18
  - cycler=0.10.0
  - decorator=4.4.0
  - docutils=0.15.2
  - eventio=0.20.1
  - freetype=2.9.1
  - gammapy=0.8
  - hdf5=1.10.4
  - idna=2.8
  - imagesize=1.1.0
  - iminuit=1.3.7
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipython_genutils=0.2.0
  - jinja2=2.10.3
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libtiff=4.0.10
  - llvmlite=0.29.0
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mock=3.0.5
  - more-itertools=7.2.0
  - ncurses=6.1
  - numba=0.45.1
  - numexpr=2.7.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - openssl=1.1.1c
  - packaging=19.2
  - pandas=0.25.1
  - pillow=6.2.0
  - pip=19.2.3
  - pluggy=0.13.0
  - psutil=5.6.3
  - py=1.8.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pysocks=1.7.1
  - pytables=3.5.2
  - pytest=5.2.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.4.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyyaml=5.1.2
  - readline=7.0
  - regions=0.4
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.4.0
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sphinx=2.2.0
  - sphinx-automodapi=0.12
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlite=3.30.0
  - tbb=2019.8
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.3
  - urllib3=1.25.6
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
